# -*- coding: utf-8 -*-
"""webscrapingwithpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_EXJdxOTubBjha-ah6n7VfgKvXyWafo

### Scrape via BeautifulSoup and Requests
"""

import requests

url = "https://blog.hubspot.com/sales/famous-quotes"

payload = {}
headers = {
  'authority': 'blog.hubspot.com',
  'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'accept-language': 'en-US,en;q=0.9,la;q=0.8,lb;q=0.7',
  'cache-control': 'max-age=0',
  'if-modified-since': 'Sat, 12 Aug 2023 16:47:14 GMT',
  'referer': 'https://www.google.com/',
  'sec-ch-ua': '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"',
  'sec-ch-ua-mobile': '?1',
  'sec-ch-ua-platform': '"Android"',
  'sec-fetch-dest': 'document',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-site': 'cross-site',
  'sec-fetch-user': '?1',
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text,'lxml')
quotes = soup.find(class_='hsg-featured-snippet__wrapper').find(class_='hsg-featured-snippet__wrapper--content').find('ol').find_all('li')
for quote in quotes:
  print(quote.text)

